### ISSUE TITLE
Cors error

### ISSUE THREAD

**Issue by Aricatofuka** [sefinek24/random-animals#25]
For api you need to add header access-control-allow-methods: * to your backend, without this header the requested methods are not available from the browser. Hope this page helps you:

https://enable-cors.org/server.html

**Comment by sefinek24** [comment]
It was the fault of the `helmet` module. I set `crossOriginResourcePolicy` to `false.` I already knew about it earlier, but I didn't want to change it because the API is for Discord `discordbot`.

**Comment by Aricatofuka** [comment]
Didn't have a problem thx.
